version: '3.8'

services:
  app:
    build: .
    container_name: reservation_app
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/azki_reservation?useSSL=false
      - SPRING_DATASOURCE_USERNAME=azki_user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_REDIS_HOST=redis
      - JWT_SECRET=your-super-strong-jwt-secret-key-that-is-very-long
    depends_on:
      - db
      - redis


  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: azki_reservation
      MYSQL_USER: azki_user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:6.2-alpine
    container_name: redis_cache
    ports:
      - "6379:6379"

volumes:
  mysql_data: