spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/azki_reservation}
    username: ${SPRING_DATASOURCE_USERNAME:azki_user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  cache:
    type: redis
  redis:
    host: ${SPRING_REDIS_HOST:localhost}
    port: 6379

flyway:
  baseline-on-migrate: true

server:
  port: 8083

auth:
  jwt:
    access-token-validity-seconds: 3600 # 1 hour
    secret: ${JWT_SECRET:default-secret-key-for-local-dev-only-change-it}