spring:
  datasource:
    url: jdbc:mysql://localhost:3306/azki_reservation
    username: azki_user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

flyway:
  baseline-on-migrate: true

server:
  port: 8083

auth:
  jwt:
    access-token-validity-seconds: 600
    secret: lp+flT+lHbG5iLFZzx7b5RA8oVa2CMewtiCsKs3y1Kw=